# Generated by Django 2.0.1 on 2018-01-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20180121_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='user',
            new_name='author',
        ),
    ]
